transmission_spectrum:	transmission_spectrum.cpp
	`root-config --cxx --cflags` -o transmission_spectrum transmission_spectrum.cpp `root-config --glibs`

dependence_plotter:	dependence_plotter.cpp
	`root-config --cxx --cflags` -o dependence_plotter dependence_plotter.cpp `root-config --glibs`
